### ISSUE TITLE
Architecture reporting as aarch64

### ISSUE THREAD

**Issue by thbeh** [avafinger/Ubuntu-18.04-LTS-Bionic-Beaver-on-H5#1]
Hi, I was testing your 4.18.5 image and notice that when I do 'uname -m' it is reporting as aarch64. There are some apps e.g. teamviewer (armhf) could not start. 

Is there a way to rectify the architecture description? Thanks

**Comment by avafinger** [comment]
aarch64 (arm64) is the 64bit architecture, you need to install support for 32bit (armhf).

Update the distro 
```
sudo apt-get update
sudo apt-get dist-upgrade
```
and then:

```
sudo dpkg --add-architecture armhf
sudo apt-get update
sudo apt-get install libc6:armhf
sudo apt-get install libstdc++6:armhf
sync
```

**Reboot:**
`sudo reboot`
