### ISSUE TITLE
Where to find format_sd.sh

### ISSUE THREAD

**Issue by thbeh** [avafinger/Ubuntu-18.04-LTS-Bionic-Beaver-on-H5#2]
Hi, I was following your instruction to create a new image -

**sudo ./format_sd.sh /dev/sdc**

but could not find format_sd.sh in your repo. Thanks

**Comment by avafinger** [comment]
https://github.com/avafinger/Ubuntu-18.04-LTS-Bionic-Beaver-on-H5/releases/tag/v0.1
